### ISSUE TITLE
Subcategories of SPICE metrics

### ISSUE THREAD

**Issue by amazingYX** [xmu-xiaoma666/LSTNet#5]
你好，非常感谢能开源这么棒的工作。我想问一下应该怎样才能获得SPICE里每一项的分数（论文中Table12）？

**Comment by xmu-xiaoma666** [comment]
可以参考这个项目哈：https://github.com/xmu-xiaoma666/ImageCaptionMetrics

**Comment by amazingYX** [comment]
非常感谢
